-- +goose Up
-- +goose StatementBegin
CREATE TABLE SERVICE_CHECKS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME INTEGER NOT NULL,
    STATE STRING NOT NULL,
    STATUS_CODE INTEGER NOT NULL,
    RESPONSE_TIME INTEGER NOT NULL,
    ENDPOINT_URL STRING NOT NULL,
    CREATED_AT DATETIME NOT NULL,
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE SERVICE_CHECKS;
-- +goose StatementEnd
